version: "3.7"
services:
  mongodb:
    image: "mongo"
  elasticsearch:
    image: "elasticsearch:6.6.0"
  redis:
    image: "redis"
  kibana:
    image: "kibana:6.6.0"
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch"
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    depends_on:
      - "mongodb"
      - "elasticsearch"
      - "redis"
    links:
      - "mongodb"
      - "elasticsearch"
      - "redis"
    # working_dir: /home/node/app
    # environment:
      # - NODE_ENV=production
    # volumes:
      # - ./:/home/node/app
    ports:
      - "8481:8080"
      # - "8081:8081"
    command: "npm run dev"
  fetch:
    build:
      context: .
      dockerfile: Dockerfile-fetch
    depends_on:
      - "mongodb"
      - "elasticsearch"
      - "redis"
    links:
      - "mongodb"
      - "elasticsearch"
      - "redis"
    command: "node fetch.js"